---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-feature-discovery
  namespace: kube-system
  labels:
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/component: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - kube-system