---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kured
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kured
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kured
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
      honorLabels: true
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'kured_.*'
          action: keep