---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - helmrelease.yaml
  # - prometheusrule.yaml

labels:
  - pairs:
      app.kubernetes.io/name: descheduler
      app.kubernetes.io/instance: descheduler
      app.kubernetes.io/part-of: kube-system
      app.kubernetes.io/managed-by: flux
    includeSelectors: true
