---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: services
  name: trilium
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      trilium:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: triliumnext/notes
              tag: v0.94.1
            env:
              TZ: UTC
              TRILIUM_DATA_DIR: &datadir /trilium-data
              TRILIUM_DATA_DIR_PERMISSIONS: 0777
              TRILIUM_DATA_DIR_OWNER: 3000
              TRILIUM_DATA_DIR_GROUP: 544
              TRILIUM_DATA_DIR_MODE: 0777
              USER_UID: 3000
              USER_GID: 544
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: trilium
        ports:
          http:
            port: 8080
    serviceMonitor:
      app:
        serviceName: trilium
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["trilium.samcloud.online"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
    persistence:
      config:
        enabled: true
        existingClaim: trilium-pvc
        globalMounts:
          - path: *datadir
