---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudflare-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudflare-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: &secret cloudflare-dns-secret
            key: api-token
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=external
      - --gateway-namespace=kube-system
    triggerLoopOnEvent: true
    policy: sync
    sources: ["crd", "gateway-httproute"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret


  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: cloudflare-dns
            patch: |-
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
          - target:
              version: v1
              kind: Deployment
              name: cloudflare-dns
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cloudflare-dns
              spec:
                template:
                  spec:
                    containers:
                      - name: external-dns
                        args:
                          - --log-level=info
                          - --log-format=text
                          - --interval=1m
                          - --events
                          - --source=crd
                          - --source=gateway-httproute
                          - --policy=sync
                          - --registry=txt
                          - --txt-owner-id=default
                          - --txt-prefix=k8s.
                          - --domain-filter=samcloud.online
                          - --provider=cloudflare
                          - --cloudflare-dns-records-per-page=1000
                          - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
                          - --crd-source-kind=DNSEndpoint
                          - --gateway-name=envoy-external
                          - --gateway-namespace=network
