---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
  # Temporarily disabled due to double base64 encoding in 1Password
  # Re-enable when certificate data is fixed or Let's Encrypt rate limit clears
  # - ./externalsecret.yaml
