---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: storage
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  timeout: 15m  # Rook-Ceph operator creates 126+ resources
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}
