---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csi-driver-nfs-controller-pdb
  namespace: storage
  labels:
    app.kubernetes.io/name: csi-driver-nfs
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: csi-nfs-controller  # More specific selector for controller pods only