enabled: true
imagePullPolicy: IfNotPresent
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
nodeSelector: {}
tolerations:
- operator: Exists
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
extraHostPathMounts: []
extraConfigmapMounts: []
daemonSetAnnotations: {}
extraVolumes: []
updateStrategy: {}
daemonSetLabelsOverride: {}
selectorLabelsOverride: {}
podLabelsOverride: {}
serviceLabelsOverride: {}

# Set DNS policy for tetragon pods.
#
# Recommended DNS policy for tetragon pod depends on whether the export container
# needs to resolve external DNS names (e.g. an S3 URL) or internal ones (e.g. a Kubernetes
# DNS name for elasticsearch service).
#
# - For external DNS names, use "Default" so that the export container continues to function
#   properly in case there is a connectivity issue between the export container and core-dns.
# - For internal DNS names, use "ClusterFirstWithHostNet" so that the export container can
#   resolve them.
#
# https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
dnsPolicy: ClusterFirstWithHostNet

# exportDirectory specifies directory to put Hubble and FGS JSON export files.
exportDirectory: "/var/run/cilium/tetragon"
# exportFileRotationInterval specifies file creation interval for hubble-export-s3.
exportFileCreationInterval: "60s"
hostNetwork: true

tetragon:
  enabled: true
  image:
    repository: quay.io/cilium/tetragon
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  securityContext:
    privileged: true

  # Process monitoring settings
  processCacheSize: 65536
  exportFilename: tetragon.log
  exportFileMaxSizeMB: 50
  exportFileMaxBackups: 5
  exportFileCompress: true
  exportRateLimit: -1

  # Enable all relevant events
  exportAllowList: |-
    {
      "event_set": [
        "PROCESS_EXEC",
        "PROCESS_EXIT",
        "PROCESS_KPROBE",
        "PROCESS_TRACEPOINT",
        "PROCESS_UPROBE"
      ]
    }

  # Filter out noisy system namespaces
  exportDenyList: |-
    {"health_check":true}
    {"namespace":["kube-system"]}

  # Enable Kubernetes integration
  enableK8sAPI: true
  enableCiliumAPI: true
  enableProcessCred: true
  enableProcessNs: true
  enablePolicyFilter: true

  # Prometheus metrics
  prometheus:
    enabled: true
    address: ""
    port: 2112
    serviceMonitor:
      enabled: false
      labels:
        release: kube-prometheus-stack

  # gRPC API for external integrations
  grpc:
    enabled: true
    address: "0.0.0.0:54321"

  # Export configuration for observability stack
  export:
    loki:
      enabled: false
      url: http://loki-gateway.observability.svc.cluster.local
      batchSize: 100
      batchWaitMs: 1000
      labels:
        app: tetragon
        component: security

    tempo:
      enabled: false
      url: http://tempo.observability.svc.cluster.local:4317
      attributes:
        service.name: tetragon
        service.namespace: kube-system

tetragonOperator:
  enabled: true
  image:
    repository: quay.io/cilium/tetragon-operator

export:
  mode: "stdout"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  filenames:
  - tetragon.log
  stdout:
    enabled: true
    image:
      repository: quay.io/cilium/hubble-export-stdout
