---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet-csr-approver