# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3uLNRJVQE5smtfjNT/h7KvLex4KFPoOxhmq1wD/+CqmZuRPr4qPJcA==,iv:QG8j9Pa82v7J2QYL1rnn7PNkWWqG5O75VwZ6g+VZqfk=,tag:cfCTCLMNbQp56ffa0VbMjg==,type:str]
sops:
  age:
    - recipient: age15vkl7aqh54mdrsury3u5sqak8yrewvzax0ckz4d5j0dqngc3puts9jf7nw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dVVFUFJTRmhsMG5BZ1NI
        blFHRGRQV0tDZWx2bXIyY0RhTG11SmcxTEJBCitvc2NzbUdDYS9VZG1jcGQ3MlBq
        NW8xUGVUYUFXZW1DWGFyUnY4REtnN3MKLS0tIFNRZXc1dFBUOG1heW5ZRHVJOWpH
        czZadlFsc2ZUTW9uWDRTNWRZSHpINXMKYj9FauW+o2nHqKZOo8T6/Gj/7VQiDXgY
        9ravx8rognEi7kOb9OX6R++gOTEuTfo7eLTfK2CLHmSmofIIokKe2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-13T17:11:23Z"
  mac: ENC[AES256_GCM,data:khlo3R6aP5q3qZ88G+jFJRK/LXN2fvQXZ6TwE0fYuRaweH3lL/63lXeG2H2X9VobbuPeTQk4q50SSI3ujbPiC89fHJcJRjy6FsUJDuXRCVlBoaKIHtaG2Zhnk8J+UI6GQsj2/nniD3nzW55VaCAPXAsNnHVGQG4hzheKdu4GY4k=,iv:DedfZLuroe4HxGkzwf3YxhI3sA1Fs70Z7mxomM0/jxo=,tag:BVSKjPnXzIVKcw61W0BTcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
