---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-problem-detector
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://bjw-s-labs.github.io/helm-charts
