---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      multus:
        type: daemonset

        pod:
          hostNetwork: true

        initContainers:
          cni-plugins:
            image:
              repository: ghcr.io/home-operations/cni-plugins
              tag: 1.8.0

        containers:
          multus:
            image:
              repository: ghcr.io/k8snetworkplumbingwg/multus-cni
              tag: v4.2.0
            command:
              - /thin_entrypoint
            args:
              - --cleanup-config-on-exit=true
            resources:
              requests:
                cpu: "10m"
              limits:
                memory: "512Mi"
            securityContext:
              privileged: true

    serviceAccount:
      multus: {}

    persistence:
      etc-cni-net-d:
        type: hostPath
        hostPath: /etc/cni/net.d
        globalMounts:
          - path: /host/etc/cni/net.d
      opt-cni-bin:
        type: hostPath
        hostPath: /opt/cni/bin
        globalMounts:
          - path: /host/opt/cni/bin

    rbac:
      roles:
        multus:
          type: ClusterRole
          rules:
            - apiGroups:
                - "k8s.cni.cncf.io"
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - "pods"
                - "pods/status"
              verbs:
                - "get"
                - "update"
            - apiGroups:
                - ""
                - "events.k8s.io"
              resources:
                - "events"
              verbs:
                - "create"
                - "patch"
                - "update"
      bindings:
        multus:
          type: ClusterRoleBinding
          roleRef:
            identifier: multus
          subjects:
            - identifier: multus
