apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:J2FCEf+AmqGkk/LJLIrY,iv:Zx3p/4DPzCXxH2PhRAqyjmihriTqsGwGw0jnGRc0k0s=,tag:ViJ255up4TvhaFgSPHiPzQ==,type:str]
sops:
  age:
    - recipient: age15vkl7aqh54mdrsury3u5sqak8yrewvzax0ckz4d5j0dqngc3puts9jf7nw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbzF3Y0l6eXNnK0NtQmwy
        UVRRTTg5UUw5SkRNUW81Q3N1V24ycjBGa2dZCk5YOTV5Y2R2aHk0TmV6TjFmZFFu
        akpOM3g2dU5nWlZVVFhBczJ1Mko0KzAKLS0tIEVROVBYU1pBRlJ4aUt4dnZJSnpR
        RXJIdDVhaXEvMlMwbnNTSHB3NmhacjgKwWChjHtLjszb+VzqtUMMFNB/l8kENQ5U
        X9l8DVD8HLOV1nYrDHmF4AAE0CaW1pjdBrpQ4xlArVjDZ7IM1/M2LQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-13T17:11:24Z"
  mac: ENC[AES256_GCM,data:JJvslf5RjVNUPurqvmJAVDMYM3maN7/UGha7TogEsc+ak96f//oeqFqA4J0ijzQFDiKX9X3EMR11VtuKF6iKTYrMWayGNTd6MAK2uskUBQqF3SC18jqPHrAmiK+rAC0xtE4VZvVosCh+FYa+amC5XcO1zXRfeUVURx9lB+7y1O0=,iv:00Ge7gwgnY9cpsV/fPVOztoO3mAOUr8nO8lZLLYHQls=,tag:tniXM+TMK4cQwxDxFHd/8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
