apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-bench
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-bench
    app.kubernetes.io/instance: kube-bench
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: kube-system
    production-grade: "true"
    security-hardened: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: kube-bench
            app.kubernetes.io/instance: kube-bench
            app.kubernetes.io/component: security
            app.kubernetes.io/part-of: kube-system
            production-grade: "true"
            security-hardened: "true"
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "8080"
        spec:
          serviceAccountName: kube-bench
          hostPID: true
          containers:
            - name: kube-bench
              image: docker.io/aquasec/kube-bench:v0.7.1
              command:
                - kube-bench
                - run
                - --targets
                - node
                - --outputfile
                - /var/log/kube-bench/results.json
                - --json
              volumeMounts:
                - name: var-lib-kubelet
                  mountPath: /var/lib/kubelet
                  readOnly: true
                - name: etc-kubernetes
                  mountPath: /etc/kubernetes
                  readOnly: true
                - name: usr-bin
                  mountPath: /usr/local/mount-from-host/bin
                  readOnly: true
                - name: config
                  mountPath: /etc/kube-bench/cfg
                - name: logs
                  mountPath: /var/log/kube-bench
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
          volumes:
            - name: var-lib-kubelet
              hostPath:
                path: /var/lib/kubelet
            - name: etc-kubernetes
              hostPath:
                path: /etc/kubernetes
            - name: usr-bin
              hostPath:
                path: /usr/bin
            - name: config
              configMap:
                name: kube-bench-config
            - name: logs
              emptyDir: {}
          restartPolicy: Never
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
