---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-bench
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # App template configuration
    nameOverride: "kube-bench"
    fullnameOverride: "kube-bench"

    resources:
      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: kube-bench
          namespace: kube-system
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: kube-bench
        rules:
          - apiGroups: [""]
            resources: ["nodes", "pods"]
            verbs: ["get", "list"]
          - apiGroups: [""]
            resources: ["nodes/proxy"]
            verbs: ["get"]
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: kube-bench
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: kube-bench
        subjects:
          - kind: ServiceAccount
            name: kube-bench
            namespace: kube-system
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: kube-bench-config
          namespace: kube-system
        data:
          config.yaml: |
            ---
            controls:
              - id: 1
                text: "Control Plane Security Configuration"
                type: "master"
              - id: 2
                text: "Etcd Node Configuration"
                type: "etcd"
              - id: 3
                text: "Control Plane Configuration"
                type: "master"
              - id: 4
                text: "Worker Node Security Configuration"
                type: "node"
              - id: 5
                text: "Kubernetes Policies"
                type: "policies"

            version_mapping:
              "1.24": "cis-1.24"
              "1.25": "cis-1.24"
              "1.26": "cis-1.24"
              "1.27": "cis-1.24"
              "1.28": "cis-1.24"

            target_mapping:
              "k8s": "k8s"
      - apiVersion: batch/v1
        kind: CronJob
        metadata:
          name: kube-bench
          namespace: kube-system
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "8080"
        spec:
          schedule: "0 0 * * *"  # Run daily at midnight
          concurrencyPolicy: Forbid
          successfulJobsHistoryLimit: 3
          failedJobsHistoryLimit: 3
          jobTemplate:
            spec:
              template:
                metadata:
                  annotations:
                    prometheus.io/scrape: "true"
                    prometheus.io/path: "/metrics"
                    prometheus.io/port: "8080"
                spec:
                  serviceAccountName: kube-bench
                  hostPID: true
                  containers:
                    - name: kube-bench
                      image: docker.io/aquasec/kube-bench:v0.13.0
                      command:
                        - kube-bench
                        - run
                        - --targets
                        - node
                        - --outputfile
                        - /var/log/kube-bench/results.json
                        - --json
                      volumeMounts:
                        - name: var-lib-kubelet
                          mountPath: /var/lib/kubelet
                          readOnly: true
                        - name: etc-kubernetes
                          mountPath: /etc/kubernetes
                          readOnly: true
                        - name: usr-bin
                          mountPath: /usr/local/mount-from-host/bin
                          readOnly: true
                        - name: config
                          mountPath: /etc/kube-bench/cfg
                        - name: logs
                          mountPath: /var/log/kube-bench
                      securityContext:
                        privileged: true
                      resources:
                        requests:
                          cpu: 100m
                          memory: 128Mi
                        limits:
                          cpu: 500m
                          memory: 256Mi
                  volumes:
                    - name: var-lib-kubelet
                      hostPath:
                        path: /var/lib/kubelet
                    - name: etc-kubernetes
                      hostPath:
                        path: /etc/kubernetes
                    - name: usr-bin
                      hostPath:
                        path: /usr/bin
                    - name: config
                      configMap:
                        name: kube-bench-config
                    - name: logs
                      emptyDir: {}
                  restartPolicy: Never
                  tolerations:
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
                      effect: NoSchedule
                    - key: node-role.kubernetes.io/master
                      operator: Exists
                      effect: NoSchedule