---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./serviceaccount.yaml
  - ./rbac.yaml
  - ./configmap.yaml
  - ./cronjob.yaml