apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-bench
  labels:
    app.kubernetes.io/name: kube-bench
    app.kubernetes.io/instance: kube-bench
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: kube-system
    production-grade: "true"
    security-hardened: "true"
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bench
  labels:
    app.kubernetes.io/name: kube-bench
    app.kubernetes.io/instance: kube-bench
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: kube-system
    production-grade: "true"
    security-hardened: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-bench
subjects:
  - kind: ServiceAccount
    name: kube-bench
    namespace: kube-system
