apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-bench
    app.kubernetes.io/instance: kube-bench
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: kube-system
    production-grade: "true"
    security-hardened: "true"
